
name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -o bb -ldflags="-s -w" main.go
    # - name: Test
    #   run: go test -v ./...


        # TODO maybe use this instead
        # https://github.com/fnkr/github-action-ghr
  # release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Go
  #     uses: actions/setup-go@v3
  #     with:
  #       go-version: 1.19
  #   - name: Build
  #     run: go build -ldflags="-s -w"
  #   - name: Upload Release
  #     uses: Roang-zero1/github-upload-release-artifacts-action@v3.0.0
  #     with:
  #       args: bb
